### ISSUE TITLE
Ejected CLI Feedback

### ISSUE THREAD

**Issue by Kaffiend** [Kaffiend/electron-angular-ngrx#5]
The aim of this seed is to have as clean an interaction and integration with the angular CLI as possible. Currently with native modules, I see no other way to handle those without ejecting the CLI, which is something I did not want to do. I'm opening this issue to get everyone's feedback as to the direction to take the seed to remain CLI friendly.

What your thoughts on ejecting the CLI?

Suggest an alternative to ejection?

**Comment by ruipimentel** [comment]
Hi @Kaffiend, thank you for this seed.

Well, my first thought on ejection is "I don't like it either" :)

It would be nice if @angular/cli handled Webpack's `"target"`setting alone, but this has already been implemented by community in [this PR](https://github.com/angular/angular-cli/pull/7435) and rejected by CLI's staff.

However, I'm actually not quite sure what to expect from automated unit and E2E tests, because as far as I know they are executed inside a regular browser window (with no "superpowers" like Electron's). How should native Node APIs behave within tests?

**Comment by Kaffiend** [comment]
Spectron will be added to test Electron and native node APIs all render process code should still be scoped to the components etc. At least that's my perspective.

**Comment by Kaffiend** [comment]
I ejected the webpack from the cli and updated the build process for HMR. added the baseline ngrx entity example (more examples planned) and added native module support in #6

**Comment by ruipimentel** [comment]
Thank you @Kaffiend for your time and effort :)

**Comment by Kaffiend** [comment]
Closed, alternative found.
